project:
  type: book
  output-dir: docs
  resources:
    - assets/**

book:
  title: ""
  # authors:
  #   - name: Rachael Blake
  #     orcid: 0000-0003-1689-0557
  #     affiliations: 
  #       - name: Intertidal Agency
  #   - Steve Formel
  #     orcid: 0000-0003-1689-0557
  #     affiliations: 
  #       - name: Formel Data Services
  #   - Kate Wing
  #     orcid: 0000-0003-1689-0557
  #     affiliations: 
  #       - name: Intertidal Agency
  chapters: 
    - index.qmd
    - data-standards.qmd
    - dwc-basics.qmd
    - align-your-data.qmd
    - resources.qmd
  page-navigation: false
  favicon: /img/Intertidal-ProfilePic-Aqua-Bold.png
  navbar: 
    title: false
    background: "#034969"
    # logo: /img/Intertidal_PrimaryLogo_Bold_White.png
    logo-href: https://intertidal.agency/
  search: 
    location: sidebar
    type: textbox
  sidebar:
    style: "floating"
    type: "light"
    background: "#034969"
    alignment: "left"
    border: false
 
  page-footer: 
    left: <img src="/img/Intertidal_PrimaryLogo_Bold_White.png" width="105">
    center: "Content licensed CC-BY 4.0, Intertidal Agency"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/company/intertidal-agency/
      - icon: github
        href: https://github.com/intertidalagency/ia-guides-resources
    background: "#0E7272"    

    
format:
  html:
    theme:
      - default
      - custom.scss
    fontcolor: "#ffffff"
    fontsize: 1.2rem
    # linkcolor: "#30ACAE"
    number-sections: false
    backgroundcolor: "#034969"
    # monobackgroundcolor: "#034969"
    toc: true
    toc-location: left
    toc-title: ""
    toc-depth: 4
    author-meta: "Intertidal Agency"
    page-layout: full
    grid:
      sidebar-width: 300px
      body-width: 2000px
      margin-width: 150px
      gutter-width: 3rem


execute:
  freeze: auto
  
  
    