---
title: Resources
format: html
---

## Guides and How-Tos

1. OBIS Manual <https://manual.obis.org/>
2. [Darwin Core Quick Reference Guide](https://dwc.tdwg.org/terms/): find specific terms

## Example Published Datasets

### eDNA

- Silliman K, Anderson S, Thompson L (2024). eDNA from Gulf of Mexico Ecosystems and Carbon Cruise 2021 (GOMECC-4). Version 1.7. United States Geological Survey. Occurrence dataset. <https://obis.org/dataset/210efc7c-4762-47ee-b4b5-22a0f436ef44>

### Large Coral Database with Images

- National Oceanic and Atmospheric Administration (NOAA), Deep Sea Coral Research and Technology Program (DSCRTP) 2025. Observations of Deep-Sea Coral and Sponge Occurrences from NOAA's National Database for Deep-sea Corals and Sponges, 1842-Present, version 20250714-0 (NCEI Accession 0145037). NOAA National Centers for Environmental Information. <https://obis.org/dataset/f5a4799e-dc24-4807-89d9-01da47d52e3b>

### Fish Trawl

- Rebecca Peters. Maine Department of Marine Resources Inshore Trawl Survey, 2000–2019. 2022. Maine Department of Marine Resources, PO Box 8, West Boothbay Harbor, Maine 04575 <https://obis.org/dataset/d4091591-a085-4cfa-9734-5f0ecf5564a8>

### Zooplankton Monitoring

- Keister J E, Winans A, Herrmann B, Kalata O, Mayorga E (2024). Puget Sound Zooplankton Monitoring Program (Salish Sea, USA), starting in 2014. Version 1.1. United States Geological Survey. Samplingevent dataset. <https://obis.org/dataset/debc8f44-f70f-4d30-821e-d3a705f62cfb>

### Passive Acoustic Monitoring (PAM)

- NOAA Office of National Marine Sanctuaries and U.S Navy (2023). Sanctuary Soundscape Monitoring Project (SanctSound) Daily Aggregated Species Detections. Version 1.1. Occurrence dataset. <https://obis.org/dataset/7a4427f6-67ee-4cc1-b95f-3045523420a1>

### Seabird Colony Observations

- Moore E, McDonald T, Schaefer A, Kaler R, Oehlers S, Renner H, Corcoran R, Boldenow M, Goldstein M, Lyons D, Renner M, Cooper E (2024). Statewide Alaska Tern Occurrences. Version 1.1. USFWS-AK. Occurrence dataset. <https://ipt-obis.gbif.us/resource?r=usfws_alaska_tern_colonies&v=1.1>

### Benthic Fauna with Sediment Isotope Data

- Demopoulos A, Prouty N, McClain Counts J, Richards K (2024). Isotope data from Shimada 2018 research expedition. Version 1.9. United States Geological Survey. Occurrence dataset. <https://obis.org/dataset/c9171650-c1fe-4b17-ab64-32b883fd738d>