name: Quarto previews (external repo)

on:
  push:
    branches: ["**"]      # run on all branches
  workflow_dispatch:

jobs:
  preview:
    if: github.ref_name != 'main'   # only non-main branches
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Render (optional preview profile)
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          # If you have a preview profile for base-url, uncomment:
          # QUARTO_PROFILE=preview \
          quarto render
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PREVIEW_TOKEN }}
          external_repository: sformel/ROSA_preview
          publish_branch: gh-pages
          publish_dir: _site
          destination_dir: previews/${{ github.ref_name }}
          keep_files: true

  # Optional: a prod job placeholder that does NOTHING, so main stays unchanged
  # (Your repo currently serves prod from main; leave it alone.)
  prod-noop:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Prod is handled by existing Pages setup from main; no CI deploy needed."
