name: Quarto branch preview

on:
  push:
    branches-ignore: [main]   # don't run previews for main
  workflow_dispatch:

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render site
        run: |
          # If you use a preview profile, uncomment the next line:
          # QUARTO_PROFILE=preview \
          quarto render

      - name: Deploy to gh-pages subdir
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site
          destination_dir: previews/${{ github.ref_name }}
          keep_files: true
